- targets:
    - '{{ cloud_app_server }}'
    - '{{ cloud_db_server }}'
  labels:
    job: node
    __metrics_path__: /metrics/node

- targets:
    - '{{ cloud_app_server }}'
  labels:
    job: nginx
    __metrics_path__: /metrics/nginx

- targets:
    - '{{ cloud_app_server }}'
  labels:
    job: cadvisor
    __metrics_path__: /metrics/cadvisor

- targets:
    - '{{ cloud_db_server }}'
  labels:
    job: mariadb
    __metrics_path__: /metrics/mariadb

- targets:
    - '{{ cloud_app_server }}'
  labels:
    job: docker
    __metrics_path__: /metrics/docker

- targets:
    - '{{ cloud_app_server }}'
  labels:
    job: gunicorn
    __metrics_path__: /metrics/gunicorn

- targets:
    - '{{ cloud_app_server }}'
  labels:
    job: process
    __metrics_path__: /metrics/process

- targets:
    - '{{ cloud_app_server }}'
  labels:
    job: rq
    __metrics_path__: /metrics/rq

- targets:
    - '{{ cloud_app_server }}'
  labels:
    job: cloud
    __metrics_path__: /metrics/cloud
